export const RECORD_MODEL = 'RECORD_MODEL';
export const RECORD_BROWSER = 'RECORD_BROWSER';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const RECORD_TOKEN = 'RECORD_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const RECORD_MENU = 'RECORD_MENU';
export const RECORD_EMPLOYEE = 'RECORD_EMPLOYEE';
export const ROUTER_ACTIVE = 'ROUTER_ACTIVE';
export const RECORD_PERMISSION = 'RECORD_PERMISSION';
export const RECORD_USER = 'RECORD_USER';
export const RECORD_MESSAGE = 'RECORD_MESSAGE';
export default {};
